action-releaser-dispatch/README.md
action-releaser-dispatch/main.sh

This change allow the action to be run by setting Version variable instead of it relying on pushed refs/tags, for example if the trigger is Workflow/Repository dispatch.

[releaser-dispatch] Test input version for semver format (instead of refs)

---

action-helm-tools/package.sh

If a subchart does not pass linting catch it earlier before deploying the chart. It also points to which subchart needs updating instead of just an error during install.

[helm-tools] Lint subcharts

---

action-helm-tools/package.sh

When chart is packaged subchart linting does not have any effect. Instead run subchart linting on the chart folder.

[helm] run linting prior to helm package

---

action-version/main.sh

Ignore tags not starting with `vX.Y.Z`

[version] git describe match tags starting with vSemVer

---

action-helm-tools/common.sh
action-helm-tools/publish.sh

The env variable `PUBLISH_TO_REGISTRY` determines if pushes go to ghcr.io or Artifactory.
If the variable is set and equal to `GHCR_HELM_DEV_REGISTRY` then the chart will be published to ghcr.io
else it will be published to Artifactory
These two PRs have succesfully published to ghcr.io from this branch:
* https://github.com/qlik-trial/messaging/pull/79
* https://github.com/qlik-trial/message-delivery-monitor/pull/195

Implement helm push to ghcr.io

---

action-helm-tools/dependencies.sh
action-helm-tools/qlikcommon-check.sh

reading qlikcommon version from resource-contract instead of relying on helm search, which doesn't work with oci registries

qlikcommon validation against resource-contract

---

action-helm-tools/common.sh
action-helm-tools/publish.sh
action-helm-tools/test.sh

Until all component repositories have switched to use QLIK_XXXX
instead of GHCR_XXXX, action-helm-tools should be able to handle
both GHCR_XXXX and QLIK_XXXX.

Handle both GHCR_XXXX and QLIK_XXXX in action-helm-tools

---

action-helm-tools/common.sh

Setting up KIND should not take more than 2 minutes, enforce a timeout so that the step does not run indefinitely in case there are issues with the runner, GitHub or download of KIND.

helm: Set KIND create timeout to 3min

---

action-helm-tools/common.sh

bitnami is the chart repo to use for minio charts.
I haven't yet found any of our QCS charts that uses `@minio`

chore: helm.min.io no longer responding

---

action-version/main.sh

This will make sure that the patch version is bumped when creating dev tags.
Example:
`v3.3.9-9-g038da41`becomes `v3.3.10-9-g038da41`
`vMAJOR.MINOR.PATCH-NUMBEROFCOMMITSSINCETAG-COMMITREF`

Quick fix for semver/bumping patch version for dev releases

---

action-version/README.md
action-version/main.sh

`git describe --tags` will produce something like `0.0.0-0-g123abc` which isn't a correct semver.
Replace last `-` with a `.` to get `0.0.0-0.g123abc`.
This is to avoid that the ASCII value of the last part counts as the highest semver instead of the intended pre-release version number.
Also see https://github.com/semver/semver/issues/394

Git describe --tags doesn't produce correct semver

---

action-version/README.md
action-version/main.sh

Reverts qlik-oss/ci-tools#148
The helm version becomes incorrect if sha starts with a 0.

Revert "Remove g"

---

action-run-cmd-create-pr/entrypoint.sh

The action is currently broken due to new safe guards of git refusing to do git operations in workspaces not owned by the executing user. This is an implementation of the proposed workaround https://github.blog/2022-04-12-git-security-vulnerability-announced/

chore: workaround for CVE-2022-24765

---

action-helm-tools/common.sh

All active component repositories now use component.yaml instead of components.yaml. Therefore, there is no longer any need to support components.yaml.

Remove support for components.yaml

---

action-helm-tools/common.sh
action-helm-tools/package.sh

merge `component.yaml` into `values.yaml`, allow using component metadata in helm chart.
proof that it works:
```
EU-etq:qdi-app-manager etq$ helm chart pull ghcr.io/qlik-trial/helm/qdi-app-manager:1.11.4-18-g6d4bcb0
1.11.4-18-g6d4bcb0: Pulling from ghcr.io/qlik-trial/helm/qdi-app-manager
ref:     ghcr.io/qlik-trial/helm/qdi-app-manager:1.11.4-18-g6d4bcb0
digest:  b6061afb7f81384bf3dffc7198c5c06892b1d7ca15da61e0fb75d535316fcf27
size:    121.9 KiB
name:    qdi-app-manager
version: 1.11.4-18-g6d4bcb0
Status: Downloaded newer chart for ghcr.io/qlik-trial/helm/qdi-app-manager:1.11.4-18-g6d4bcb0
EU-etq:qdi-app-manager etq$ cd /tmp
EU-etq:tmp etq$ helm chart export ghcr.io/qlik-trial/helm/qdi-app-manager:1.11.4-18-g6d4bcb0
ref:     ghcr.io/qlik-trial/helm/qdi-app-manager:1.11.4-18-g6d4bcb0 …
```

feature: merge component into values file

---

action-helm-tools/dependencies.sh

* no need to filter out intermediate artifacts.
* much smaller list, so no need to use pagination to retrieve latest releases (at least until we have 100 releases).

bugfix: query qlik-prod instead of qlik-trial for own chart releases

---

action-helm-tools/common.sh
action-helm-tools/publish.sh
action-helm-tools/test.sh

The "Package helm" workflow, which uses action-helm-tools, should be closer integrated with Qlik Releaser. Therefore, similar to Qlik Releaser, action-helm-tools should use environment variables GITHUB_USER and GITHUB_TOKEN instead of
QLIK_DOCKER_DEV_USERNAME
QLIK_HELM_DEV_USERNAME
QLIK_DOCKER_DEV_PASSWORD
QLIK_HELM_DEV_PASSWORD
and use hard coded values "ghcr.io/qlik-trial" and "ghcr.io/qlik-trial/helm" instead of environment variables QLIK_DOCKER_DEV_REGISTRY and QLIK_HELM_DEV_REGISTRY.

Remove dependencies to QLIK_XXXX

---

scripts-circleci/github-package-helm-dispatch.sh
scripts-jenkins/github-package-helm-dispatch.sh

**This PR should be merged after the next major QR release, when qr_package-helm-chart.yaml is available in all component repositories.** All components whose build script runs scripts-circleci/github-package-helm-dispatch.sh or scripts-jenkins/github-package-helm-dispatch.sh (i.e. most, possibly all, components which publish helm charts and build with CCI or Jenkins) will then start to use `qlik-releaser/.github/workflows/rt_package-helm-chart.yaml` instead of `<component repo root>/.github/workflows/package-helm.yaml` for packaging and publishing helm charts. For some component repositories, this might be inappropriate. In those repositories, a rollback to the old solution, i.e. using package-helm.yaml, can be done by addition of
`export GITHUB_WORKFLOW=package-helm.yaml`
before the …

Use qr_package-helm-chart.yaml instead of package-helm.yaml

---

action-verify-compliance/action.yml

actions/setup-go v3 should be used instead of actions/setup-go v2, to prevent GH from warning about "Node.js 12 actions are deprecated".

Bump from v2 to v3 for actions/setup-go

---

action-docker-sha256/main.sh
action-verify-compliance/action.yml
action-version/main.sh

In Github workflows, the syntax
`echo "::set-output name=<name>::<value>"`
is obsolete, and should be replaced with
`echo "<name>=<value>" >> $GITHUB_OUTPUT`

Use new syntax for setting wf job outputs

---

action-helm-tools/common.sh

Signed-off-by: Amir <amirghotbi@gmail.com>
jetstack:
- Contains the cert-manager helm chart
- [Ref](https://cert-manager.io/docs/installation/helm/#1-add-the-helm-repository)
twin:
- Contains the aws-eks-asg-rolling-update-handler helm chart
- [Ref](https://github.com/TwiN/aws-eks-asg-rolling-update-handler#deploying-with-helm)

Add twin and jetstack publc repos

---

action-helm-tools/common.sh

Signed-off-by: Amir <amirghotbi@gmail.com>
Argo CD:
- Contains the argo-cd helm chart
- [Ref](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#installing-the-chart)

[ArgoCD] Add AtgoCD Helm repo

---

scripts-circleci/github-package-helm-dispatch.sh
scripts-jenkins/github-package-helm-dispatch.sh

The change
Support dependency_update and action via env. variables
was reverted, since it is not yet supported by distributed qr_package-helm-chart.yaml files. The change should be done after distribution of the next major QR release (v38.0.0).

Revert "Support dependency_update ..."

---

action-helm-tools/common.sh

Add teleport as a public repo
fixes:
```
==> Helm dependency build
90
Error: no repository definition for @teleport. Please add them via 'helm repo add'
91
Error: Process completed with exit code 1.
```

Add teleport as a public repo

---

action-print-event-info/action.yml

ci-tools/action-print-event-info has been deprecated for a month. So ci-tools/action-print-event-info should now fail when it is used, with a message that qlik-releaser/.github/actions/print-event-info should be used instead. In yet another month, ci-tools/action-print-event-info should be removed.

Do exit 1 in ci-tools/action-print-event-info

---

action-helm-tools/helm-deployment-check.sh

This PR should be merged only if it does not clutter the GH workflow log too much.

Always print logs for all pods in helm-deployment-check.sh

---

action-helm-tools/common.sh

With this change, if CHART_DIR is not set, then action-helm-tools
sets CHART_DIR to manifests/chart/${CHART_NAME} if that dir exist
else
sets CHART_DIR to manifests/${CHART_NAME}/chart/${CHARTNAME} if that dir exists
else
terminates with an error message and exit 1

Improve chart dir handling in action-helm-tools

---

action-helm-tools/common.sh

Update to latest helm version to get OCI labels added when pushing helm charts to OCI registries (ghcr.io/qlik-xxx and ECR)

chore: bump helm version to 3.12.2
