action-verify-compliance/README.md, action-verify-compliance/action.yml
This PR is dependent on https://github.com/qlik-trial/mre/pull/209
=> Use TARGET_OWNER parameter in action-verify-compliance

action-helm-tools/common.sh, action-helm-tools/helm-deployment-check.sh, action-helm-tools/package.sh, action-helm-tools/test.sh
https://github.com/qlik-trial/ci-templates/issues/43
Tested with "test repo" https://github.com/qlik-trial/ci-tools-test/pull/1
=> Upgrade to helm3

action-releaser-dispatch/README.md, action-releaser-dispatch/main.sh
This change is motivated by https://github.com/qlik-trial/mre/pull/246
=> Support branch_to_release_from in action-releaser-dispatch

action-helm-tools/README.md, action-helm-tools/common.sh, action-helm-tools/dependencies.sh, action-helm-tools/main.sh, action-helm-tools/package.sh
Check if there are newer version of internal helm chart dependencies and create PR with updates
=> [helm-tools] Update helm dependencies; upgrade yq version and syntax

action-releaser-dispatch/README.md, action-releaser-dispatch/main.sh
=> Revert "Change 'pre-release' to 'draft release'"

action-releaser-dispatch/README.md, action-releaser-dispatch/main.sh
=> Change 'pre-release' to 'draft release'

action-releaser-dispatch/main.sh, action-repository-dispatch/main.sh, action-workflow-dispatch/main.sh, scripts-circleci/github-package-helm-dispatch.sh, scripts-jenkins/github-package-helm-dispatch.sh
Example:
```
HTTP/2 204 
server: GitHub.com
date: Wed, 24 Mar 2021 09:12:19 GMT
x-oauth-scopes: admin:enterprise, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, gist, repo, workflow, write:packages
x-accepted-oauth-scopes: 
x-github-media-type: github.v3; format=json
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4967
x-ratelimit-reset: 1616578782
x-ratelimit-used: 33
```
=> Return GitHub headers on api call (curl)

action-helm-tools/common.sh
=> Update to new jfrog cli fetch

action-helm-tools/common.sh, action-helm-tools/test.sh
These two draft PRs show that referencing charts and docker images in GHCR works with this PR:
* https://github.com/qlik-trial/messaging/pull/70
* https://github.com/qlik-trial/message-delivery-monitor/pull/190
Remaining part is to publish to GHCR, but that will be a subsequent PR
PR to validate that non-touched workflows are not broken:
https://github.com/qlik-trial/message-delivery-monitor/pull/191
=> Add ghcr.io support

action-helm-tools/publish.sh
...instead of the expanded chart in the chart directory (as the chart in the chart directory has version 0.0.0)
=> Saving packaged chart for push to ghcr.io

action-docker-sha256/README.md, action-docker-sha256/action.yml, action-docker-sha256/main.sh
required for signing docker images, to avoid duplicating this code.
=> added docker-sha256 actions

action-helm-tools/dependencies.sh
=> Revert "fix: avoid picking up old content from existing branch"

action-helm-tools/common.sh
Adding infracloudio repository for fixing botkube chart packaging.
=> Add infracloudio for botkube

scripts-circleci/github-package-helm-dispatch.sh
=> Set correct commit_sha in github-package-helm-dispatch.sh

action-helm-tools/common.sh
Ref.: https://github.com/DataDog/helm-charts
Signed-off-by: Masaru Hoshi <masaru.hoshi@qlik.com>
=> Datadog Helm Repository

action-helm-tools/common.sh, action-helm-tools/publish.sh
successful run: https://github.com/qlik-trial/replicate-agent-service/actions/runs/3477608519/jobs/5814608053
=> chore: kind v0.17.0 + helm v3.10.2

scripts-circleci/github-package-helm-dispatch.sh, scripts-jenkins/github-package-helm-dispatch.sh
This PR should be merged next year, together with https://github.com/qlik-trial/qix-sessions/pull/3538
=> Remove code for handling commitsha parameter in package-helm.yaml

action-helm-tools/common.sh
Signed-off-by: Masaru Hoshi <masaru.hoshi@qlik.com>
=> Add Dynatrace repo

action-helm-tools/common.sh
Reference: https://charts.botkube.io/
=> [botkube] Add botkube helm repo

scripts-circleci/github-package-helm-dispatch.sh, scripts-jenkins/github-package-helm-dispatch.sh
QR v38.0.0 has been distributed, so this PR should be OK to merge
=> Support dependency_update and action via env. variables (#197)

action-helm-tools/common.sh
Signed-off-by: Masaru Hoshi <masaru.hoshi@qlik.com>
=> Add karpenter helm repo

action-print-event-info/README.md, action-print-event-info/action.yml
=> Revert "Delete action-print-event-info directory"

action-helm-tools/main.sh, action-helm-tools/qlikcommon-check.sh, scripts-circleci/github-cosign-dispatch.sh, scripts-circleci/github-package-helm-dispatch.sh, scripts-jenkins/github-package-helm-dispatch.sh
For details, see https://github.com/qlik-trial/qlik-releaser/issues/2653
=> Specify GH Rest API version in HTTP call header

action-helm-tools/common.sh
add dependency for tracing chart
add dependency for hashicorp vault
=> add tracing helm dep

action-helm-tools/common.sh, action-helm-tools/package.sh
And add talend helm repository with alias `@talend`
=> chore: add revision as annotation to get OCI label

action-verify-compliance/README.md, action-verify-compliance/action.yml
=> Revert "Delete action-verify-compliance directory"
